FROM node:24-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_PUBLISHABLE_KEY
ARG VITE_SITE_URL
ARG VITE_BANK_NAME
ARG VITE_BANK_ACCOUNT_NUMBER
ARG VITE_BANK_ACCOUNT_HOLDER
ARG VITE_SUPPORT_EMAIL
ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL VITE_SUPABASE_PUBLISHABLE_KEY=$VITE_SUPABASE_PUBLISHABLE_KEY VITE_SITE_URL=$VITE_SITE_URL VITE_BANK_NAME=$VITE_BANK_NAME VITE_BANK_ACCOUNT_NUMBER=$VITE_BANK_ACCOUNT_NUMBER VITE_BANK_ACCOUNT_HOLDER=$VITE_BANK_ACCOUNT_HOLDER VITE_SUPPORT_EMAIL=$VITE_SUPPORT_EMAIL
RUN npm run build

FROM node:24-alpine AS runtime
WORKDIR /app
ENV NODE_ENV=production HOST=0.0.0.0 PORT=3000
COPY --from=build --chown=node:node /app/.output ./.output
USER node
EXPOSE 3000
CMD ["node", ".output/server/index.mjs"]

